sudo: true
language: python
cache: pip
python:
- '3'
env:
  global:
  - AWS_DEFAULT_REGION=eu-west-1
  - AWS_DEFAULT_OUTPUT=json
  - secure: AjFuCXh+SdOuk2VYRFahhurJj1MkNJk/fFYOPdaLHcCS633i9Z/76v8jom2XSSAVRaRQJj6CeeJN5TONKL/yOA1IzSijhSJPveX9FZN35OmaV2RtAcAVoIBIkGuOYPCuyLI6D6VSD9Py1zTVUkYITusuPLUTtch9P/2saEo4iIQyWq9gmvA5InxVEBX2soopgt0XIBsj2RiUAiE3eOIDOlnK44AycRVZG2oDf3eokhcOFMnSh4pPHFDPdFXrfpZJhuxqKivWaRrZ/ZmtP/K27KWa9zw+AoEmcOyUqpnaUYD1qRMFb9NeOBmJnytepNWGIkNeGF+lWysxsCLxNWygJPPGD4RANTr+iGlBkQavabuIjSmoEs5s9iU8XAneJsk3W7yKTs6VJMTF7z36fZFdtKKy/LerpSotyBY9eXZJiHLD8V3s8leUiTYmu8SCPgiK/t7+JSRIlaEv6VOf9GpYDsJIBRk0Dz6PFGh+2+nc8ecSh2qrmdZKb0LOSmKTZsZ0y9YyQHpxYpSzyoAGg6v0g2QFKquevLbLfC0fYt2VUkJ7FPZ1PDtoeDb9TewB/BXoyKhQDroH/hr9+2UI2pMY8UWXofnF0/K2nEKInhFifR6nBXP/owOXnu6vl4GwvvUbw3rKWqa+xt99kbfO6ulDZOXii9NWldIxPBMSX0ebyK8=
  - secure: TI6qdAkys2fY6R9Qvlz5Nw9zv+5R60HrwKbSd0fvPLnSVDMJCaTUaKdpdHRCS+gmpEnr7b50yDV3IQwM7dAqey2ZtC3jh9kqray5/xlfJCIPenka4Ed3oc7wMN9LGYeO++vMDgdXGLDCT03cG/fcU+TZ+GU8dRAkYU+z66qtfz8HNVtvdYz4SWAD/lStSCrkHHwr7kLiZo4aBQb8ga3e2KEWlQ55DFQUe30aoOty3cEKuRthCZiYiOA0PcZr59w2S1eVwiX9E8rtmUZnBl+KiQeip/EFso1GGJLbKUh6fCAxE6pO7QPZOM0/WZ+uYs7l0MY2VUPHIbiXj5ZvBwUnd/SXdY1LIgX/RzwtJ0Ag5blViDg6U+TobfNRY38o96yhbesCpsDbMJfFlWWIFWAlsrWIWNHwHJyHJD7u9L+FsZ3VjMabs91QN2UonBViQ7Zl+Geme0Ur8lJt23PSjI8y5LjebqsXBDt0EPwOThA3leIQDidu+eykaeDzlISuDJYnhSGmW/FWXE9GIEFtOJH5zUgQhqWWyO9Bleeo2wovMJIdWN9Crs5hCdDjxDUphuz4Y1x+PIc3m8xyy2t/F3h+B8Zm/9Dc7wHGHrxA8gU7f9aNKXND1CpcULfm8uvyrjq8jbTl65MlgU1QbfVTXDG94OS/MPUvExk9pucuoVF6cRY=
addons:
  postgresql: '9.4'
services:
- postgresql
- redis-server
before_install:
  - export BOTO_CONFIG=/dev/null
install:
- export PATH=$HOME/.local/bin:$PATH
- pip install codecov
- pip install pytest-cov
- pip install pipenv
- pipenv install --dev --skip-lock
script:
- pytest --cov
after_success:
 - codecov
notifications:
  on_pull_requests: false
